[package]
name = "primitives"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[lib]
doctest = false

[dependencies]
rustc-hex = "2"
bitcoin_hashes = "0.11"
byteorder = "1.0"
uint = "0.9.3"
